version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Bratislava
    open-pull-requests-limit: 2
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /clients/web
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Bratislava
    open-pull-requests-limit: 2
    groups:
      web-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Bratislava
    open-pull-requests-limit: 2
    groups:
      workflow-actions:
        patterns:
          - "*"
