/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/altar/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["getAltarStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["getBridgeSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/consents/{consent_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consent */
        post: operations["decideBridgeConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["streamBridgeRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CreateSession */
        post: operations["createBridgeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SessionSnapshot */
        get: operations["getBridgeSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/sessions/{session_id}/inspector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspector */
        get: operations["getBridgeSessionInspector"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send */
        post: operations["sendBridgeMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue */
        get: operations["getLoomCatalogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loom/{workflow}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View */
        get: operations["getLoomWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loom/{workflow}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["getLoomWorkflowSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["getNexusSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan */
        get: operations["getNexusPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus/swaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Swap */
        post: operations["createNexusSwap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus/swaps/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SwapStatus */
        get: operations["getNexusSwap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus/swaps/{ticket_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SwapEvents */
        get: operations["streamNexusSwapEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AltarStatus */
        AltarStatus: {
            pending_consents: number;
        };
        /** BridgeSnapshot */
        BridgeSnapshot: {
            pending_consents: components["schemas"]["ConsentCard"][];
            pending_count: number;
            session: components["schemas"]["SessionView"] | null;
            sessions: components["schemas"]["SessionSummary"][];
        };
        /** BridgeTurnView */
        BridgeTurnView: {
            content: string;
            /** Format: date-time */
            created_at: string;
            fragments?: string[];
            /** @enum {string} */
            role: "user" | "agent";
            run_id?: string | null;
            /** @default settled */
            state: string;
        };
        /** ConsentCard */
        ConsentCard: {
            args: {
                [key: string]: unknown;
            };
            id: string;
            run_id: string;
            /** @default  */
            session_id: string;
            /**
             * @default pending_consent
             * @enum {string}
             */
            state: "pending_consent" | "consented" | "refused";
            tool_name: string;
            vision: string;
        };
        /** ConsentDecisionIntent */
        ConsentDecisionIntent: {
            /** @enum {string} */
            verdict: "approve" | "deny";
        };
        /** ConsentDecisionResult */
        ConsentDecisionResult: {
            consent: components["schemas"]["ConsentCard"];
            pending_count: number;
        };
        /** LoomSummary */
        LoomSummary: {
            description: string;
            name: string;
            title: string;
            trigger_hint: string;
        };
        /** LoomView */
        LoomView: {
            description: string;
            mermaid_source: string;
            name: string;
            node_names: string[];
            title: string;
            trigger_hint: string;
        };
        /** MessageAccepted */
        MessageAccepted: {
            run_id: string;
            turn: components["schemas"]["BridgeTurnView"];
        };
        /** MessageIntent */
        MessageIntent: {
            prompt: string;
        };
        /** NexusBoard */
        NexusBoard: {
            covens: [
                string,
                components["schemas"]["NexusCovenRow"][]
            ][];
            portals: components["schemas"]["NexusCovenRow"][];
        };
        /** NexusCovenRow */
        NexusCovenRow: {
            animator_name: string;
            capability_key: string;
            dedicated: boolean;
            family: string;
            health: string;
            is_active: boolean;
            model_id: string;
            persistent_resident: boolean;
            reason: string | null;
            runtime: string;
            /** @enum {string} */
            state: "active" | "warm" | "awaited" | "warming" | "cold" | "fault";
            warm: boolean;
        };
        /** NexusSnapshot */
        NexusSnapshot: {
            board: components["schemas"]["NexusBoard"];
        };
        /** RunEventEnvelope */
        RunEventEnvelope: {
            /** @enum {string} */
            kind: "token" | "status" | "node" | "fragment" | "consent" | "log" | "done" | "resync";
            /** Format: date-time */
            occurred_at: string;
            payload: {
                [key: string]: unknown;
            };
            run_id: string;
            /**
             * @default 1
             * @constant
             */
            schema_version: 1;
            seq: number;
        };
        /** SessionCreated */
        SessionCreated: {
            session: components["schemas"]["SessionView"];
        };
        /** SessionInspector */
        SessionInspector: {
            pending_count: number;
            session_id: string;
            title: string | null;
            turn_count: number;
        };
        /** SessionSummary */
        SessionSummary: {
            /** Format: date-time */
            created_at: string;
            id: string;
            title: string;
        };
        /** SessionView */
        SessionView: {
            /** Format: date-time */
            created_at: string;
            id: string;
            title: string;
            turns?: components["schemas"]["BridgeTurnView"][];
        };
        /** SwapAccepted */
        SwapAccepted: {
            ticket: components["schemas"]["SwapTicket"];
        };
        /** SwapIntent */
        SwapIntent: {
            target: string;
        };
        /** SwapTicket */
        SwapTicket: {
            action_type: string;
            id: string;
            /** @enum {string} */
            state: "warming" | "settled" | "failed";
            target: string;
            total_metabolic_cost: number;
        };
        /** TransitionEventEnvelope */
        TransitionEventEnvelope: {
            /**
             * @default 1
             * @constant
             */
            schema_version: 1;
            seq: number;
            ticket: components["schemas"]["SwapTicket"];
        };
        /** TransitionPlan */
        TransitionPlan: {
            /**
             * @description The physical intensity of the transition
             * @enum {string}
             */
            action_type: "HARD_SWAP" | "SOFT_SWAP" | "NO_OP";
            /** @description Animator ids selected for stop/eviction */
            evict_coven_ids: string[];
            /** @description Animator ids selected for start/activation */
            launch_coven_ids: string[];
            /**
             * @description Name of the switch policy that produced this plan
             * @default
             */
            policy: string;
            /** @description Optional human-readable rationale for the plan */
            reason?: string | null;
            /** @description Number of animator evictions selected for the transition */
            total_metabolic_cost: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAltarStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AltarStatus"];
                };
            };
        };
    };
    getBridgeSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BridgeSnapshot"];
                };
            };
        };
    };
    decideBridgeConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentDecisionIntent"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentDecisionResult"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    streamBridgeRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned semantic run events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["RunEventEnvelope"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    createBridgeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
        };
    };
    getBridgeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BridgeSnapshot"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    getBridgeSessionInspector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInspector"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    sendBridgeMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIntent"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageAccepted"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    getLoomCatalogue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoomSummary"][];
                };
            };
        };
    };
    getLoomWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoomView"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    getLoomWorkflowSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    getNexusSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NexusSnapshot"];
                };
            };
        };
    };
    getNexusPlan: {
        parameters: {
            query: {
                target: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionPlan"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    createNexusSwap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwapIntent"];
            };
        };
        responses: {
            /** @description Request accepted, processing continues off-line */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapAccepted"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    getNexusSwap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapAccepted"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    streamNexusSwapEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned semantic transition events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["TransitionEventEnvelope"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
}
