/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/altar/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["getAltarStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["getBridgeSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/consents/{consent_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consent */
        post: operations["decideBridgeConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** RunSnapshot */
        get: operations["getBridgeRunSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CancelRun */
        post: operations["cancelBridgeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["streamBridgeRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CreateSession */
        post: operations["createBridgeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SessionSnapshot */
        get: operations["getBridgeSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/sessions/{session_id}/inspector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspector */
        get: operations["getBridgeSessionInspector"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridge/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send */
        post: operations["sendBridgeMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue */
        get: operations["getLoomCatalogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loom/source/patterns/{pattern_id}/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** RevisionSource */
        get: operations["getLoomPatternRevisionSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loom/source/workflows/{workflow}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["getLoomWorkflowSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loom/{pattern_id}/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revision */
        get: operations["getLoomPatternRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loom/{workflow}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View */
        get: operations["getLoomWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["getNexusSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan */
        get: operations["getNexusPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus/swaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Swap */
        post: operations["createNexusSwap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus/swaps/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SwapStatus */
        get: operations["getNexusSwap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus/swaps/{ticket_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SwapEvents */
        get: operations["streamNexusSwapEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nexus/transitions/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TransitionStatus */
        get: operations["getNexusTransition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orb/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["getOrbRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AltarStatus */
        AltarStatus: {
            csrf: components["schemas"]["CsrfClientContract"];
            pending_consents: number;
        };
        /** BridgeSnapshot */
        BridgeSnapshot: {
            active_runs: components["schemas"]["RunProjectionSnapshot"][];
            pending_consents: components["schemas"]["ConsentCard"][];
            pending_count: number;
            session: components["schemas"]["SessionView"] | null;
            sessions: components["schemas"]["SessionSummary"][];
        };
        /** BridgeTurnView */
        BridgeTurnView: {
            content: string;
            /** Format: date-time */
            created_at: string;
            fragments?: {
                [key: string]: unknown;
            }[];
            /** @enum {string} */
            role: "user" | "agent";
            run_id?: string | null;
            /** @default settled */
            state: string;
        };
        /** ConsentCard */
        ConsentCard: {
            args: {
                [key: string]: unknown;
            };
            id: string;
            run_id: string;
            /** @default  */
            session_id: string;
            /**
             * @default pending_consent
             * @enum {string}
             */
            state: "pending_consent" | "consented" | "refused" | "cancelled";
            tool_name: string;
            vision: string;
        };
        /** ConsentDecisionIntent */
        ConsentDecisionIntent: {
            /** @enum {string} */
            verdict: "approve" | "deny";
        };
        /** ConsentDecisionResult */
        ConsentDecisionResult: {
            consent: components["schemas"]["ConsentCard"];
            pending_count: number;
        };
        /** CsrfClientContract */
        CsrfClientContract: {
            cookie_name: string;
            header_name: string;
        };
        /** DelegatedJobEventView */
        DelegatedJobEventView: {
            event_id: string;
            kind: string;
            /** Format: date-time */
            occurred_at: string;
            seq: number;
            status: string;
        };
        /** DelegatedJobSummary */
        DelegatedJobSummary: {
            artifact_count: number;
            error_present: boolean;
            events: components["schemas"]["DelegatedJobEventView"][];
            events_truncated: boolean;
            job_id: string;
            output_present: boolean;
            profile: string;
            request_id: string;
            runtime: string;
            status: string;
            step_id: string;
        };
        /** DelegatedRuntimeObservation */
        DelegatedRuntimeObservation: {
            /** @constant */
            capacity_posture: "not_configured";
            coffin_profiles: string[];
            delivery: string;
            display_name: string;
            limitations: string[];
            /** @enum {string} */
            provider_gate: "not_required" | "required_unavailable";
            provider_id: string;
            runnable: boolean;
            runtime_id: string;
            transport: string;
        };
        /** EvidenceGap */
        EvidenceGap: {
            /**
             * @default unknown_or_omitted
             * @constant
             */
            classification: "unknown_or_omitted";
            end_seq: number;
            start_seq: number;
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** @enum {string} */
            capture: "process_local" | "durable_best_effort";
            event_id: string;
            kind: string;
            nexus_path?: string | null;
            /** Format: date-time */
            occurred_at: string;
            occurrence_id?: string | null;
            phase?: string | null;
            seq: number;
            subject_key?: string | null;
            summary: string;
            transition_request_id?: string | null;
        };
        /** FrameworkError */
        FrameworkError: {
            detail: string;
            extra?: {
                [key: string]: unknown;
            } | unknown[] | null;
            status_code: number;
        };
        /** LoomEdgeView */
        LoomEdgeView: {
            key: string;
            relation: string;
            source: string;
            target: string;
        };
        /** LoomNodeView */
        LoomNodeView: {
            key: string;
            kind: string;
            label: string;
        };
        /** LoomSummary */
        LoomSummary: {
            active: boolean;
            default: boolean;
            description: string;
            detail_path: string;
            digest: string;
            entry_node: string;
            implementation_revision: string;
            pattern_id: string;
            revision: string;
            route_rank: number | null;
            title: string;
            trigger_hint: string;
        };
        /** LoomView */
        LoomView: {
            checkpoint_schema: string;
            description: string;
            digest: string;
            edges: components["schemas"]["LoomEdgeView"][];
            entry_node: string;
            implementation_revision: string;
            mermaid_source: string;
            nodes: components["schemas"]["LoomNodeView"][];
            pattern_id: string;
            /** @constant */
            publication: "published";
            revision: string;
            schema_version: number;
            title: string;
            trigger_hint: string;
        };
        /** MessageAccepted */
        MessageAccepted: {
            /** @enum {string} */
            evidence_capture: "process_local" | "durable_best_effort";
            loom_path: string;
            orb_path: string;
            pattern_id: string;
            pattern_revision: string;
            run_id: string;
            turn: components["schemas"]["BridgeTurnView"];
        };
        /** MessageIntent */
        MessageIntent: {
            prompt: string;
            /** Format: uuid */
            request_id: string;
        };
        /** NexusBoard */
        NexusBoard: {
            covens: [
                string,
                components["schemas"]["NexusCovenRow"][]
            ][];
            portals: components["schemas"]["NexusCovenRow"][];
        };
        /** NexusCovenRow */
        NexusCovenRow: {
            animator_name: string;
            capability_key: string;
            checked_at: string | null;
            dedicated: boolean;
            family: string;
            health: string;
            is_active: boolean;
            model_id: string;
            persistent_resident: boolean;
            reason: string | null;
            runtime: string;
            /** @enum {string} */
            state: "active" | "warm" | "awaited" | "warming" | "cold" | "fault";
            warm: boolean;
        };
        /** NexusSnapshot */
        NexusSnapshot: {
            board: components["schemas"]["NexusBoard"];
            containment_reason: string | null;
            delegated_runtimes: components["schemas"]["DelegatedRuntimeObservation"][];
            /** Format: date-time */
            snapshot_at: string;
            transitions: components["schemas"]["TransitionRecordView"][];
        };
        /** OrbRunSnapshot */
        OrbRunSnapshot: {
            /** @enum {string} */
            capture: "process_local" | "durable_best_effort";
            delegated_jobs: components["schemas"]["DelegatedJobSummary"][];
            evidence: components["schemas"]["EvidenceItem"][];
            gaps: components["schemas"]["EvidenceGap"][];
            has_more: boolean;
            known_omissions: string[];
            ledger_head_seq: number;
            /**
             * @default not_available
             * @constant
             */
            live_tail: "not_available";
            next_after_seq: number | null;
            page_end_seq: number | null;
            pattern: components["schemas"]["PatternReference"];
            run: components["schemas"]["OrbRunSummary"];
            /**
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Format: date-time */
            snapshot_at: string;
        };
        /** OrbRunSummary */
        OrbRunSummary: {
            bridge_path: string;
            /** Format: date-time */
            created_at: string;
            error_present: boolean;
            finished_at: string | null;
            run_id: string;
            session_id: string;
            started_at: string | null;
            status: string;
            workflow_name: string;
        };
        /** PatternReference */
        PatternReference: {
            digest: string | null;
            exact: boolean;
            loom_path: string | null;
            pattern_id: string;
            revision: string;
        };
        /** RunEventEnvelope */
        RunEventEnvelope: {
            event_id: string;
            /** @enum {string} */
            kind: "token" | "status" | "node" | "dispatch" | "transition" | "fragment" | "consent" | "log" | "done" | "resync";
            /** Format: date-time */
            occurred_at: string;
            payload: {
                [key: string]: unknown;
            };
            run_id: string;
            /**
             * @default 1
             * @constant
             */
            schema_version: 1;
            seq: number;
        };
        /** RunProjectionSnapshot */
        RunProjectionSnapshot: {
            activity: string;
            capability_key: string | null;
            content: string;
            cursor: number;
            delegated_job_id: string | null;
            delegated_profile: string | null;
            delegated_runtime: string | null;
            delegated_status: string | null;
            dispatch_occurrence_id: string | null;
            /** @enum {string} */
            evidence_capture: "process_local" | "durable_best_effort";
            fragments: {
                [key: string]: unknown;
            }[];
            grant_id: string | null;
            loom_path: string | null;
            occurrence_id: string | null;
            orb_path: string;
            pattern_id: string;
            pattern_revision: string;
            run_id: string;
            run_status: string;
            /**
             * @default 1
             * @constant
             */
            schema_version: 1;
            session_id: string;
            terminal: boolean;
            transition_occurrence_id: string | null;
            transition_phase: string | null;
            transition_request_id: string | null;
        };
        /** SessionCreated */
        SessionCreated: {
            session: components["schemas"]["SessionView"];
        };
        /** SessionInspector */
        SessionInspector: {
            pending_count: number;
            session_id: string;
            title: string | null;
            turn_count: number;
        };
        /** SessionSummary */
        SessionSummary: {
            /** Format: date-time */
            created_at: string;
            id: string;
            title: string;
        };
        /** SessionView */
        SessionView: {
            /** Format: date-time */
            created_at: string;
            id: string;
            title: string;
            turns?: components["schemas"]["BridgeTurnView"][];
        };
        /** SwapAccepted */
        SwapAccepted: {
            ticket: components["schemas"]["SwapTicket"];
        };
        /** SwapIntent */
        SwapIntent: {
            request_id: string;
            target: string;
        };
        /** SwapTicket */
        SwapTicket: {
            action_type: string;
            compensation_transition_id: string | null;
            id: string;
            phase: string;
            physical_transition_id: string | null;
            request_id: string;
            /** @enum {string} */
            state: "warming" | "settled" | "failed";
            target: string;
            total_metabolic_cost: number;
        };
        /** TransitionEventEnvelope */
        TransitionEventEnvelope: {
            /**
             * @default 1
             * @constant
             */
            schema_version: 1;
            seq: number;
            ticket: components["schemas"]["SwapTicket"];
        };
        /** TransitionPlan */
        TransitionPlan: {
            /**
             * @description The physical intensity of the transition
             * @enum {string}
             */
            action_type: "HARD_SWAP" | "SOFT_SWAP" | "NO_OP";
            /** @description Animator ids selected for stop/eviction */
            evict_coven_ids: string[];
            /** @description Animator ids selected for start/activation */
            launch_coven_ids: string[];
            /**
             * @description Name of the switch policy that produced this plan
             * @default
             */
            policy: string;
            /** @description Optional human-readable rationale for the plan */
            reason?: string | null;
            /** @description Number of animator evictions selected for the transition */
            total_metabolic_cost: number;
        };
        /** TransitionRecordView */
        TransitionRecordView: {
            action_type: string | null;
            bridge_path: string | null;
            compensation_transition_id: string | null;
            detail: string | null;
            /** Format: date-time */
            observed_at: string;
            occurrence_id: string | null;
            orb_path: string | null;
            phase: string;
            physical_transition_id: string | null;
            priority: number;
            request_id: string;
            /** Format: date-time */
            requested_at: string;
            run_id: string | null;
            /** @enum {string} */
            source: "run" | "operator";
            target_capability_key: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAltarStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AltarStatus"];
                };
            };
        };
    };
    getBridgeSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BridgeSnapshot"];
                };
            };
        };
    };
    decideBridgeConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentDecisionIntent"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentDecisionResult"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    getBridgeRunSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunProjectionSnapshot"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    cancelBridgeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunProjectionSnapshot"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    streamBridgeRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned semantic run events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["RunEventEnvelope"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    createBridgeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
        };
    };
    getBridgeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BridgeSnapshot"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    getBridgeSessionInspector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInspector"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    sendBridgeMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIntent"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageAccepted"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    getLoomCatalogue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoomSummary"][];
                };
            };
        };
    };
    getLoomPatternRevisionSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pattern_id: string;
                revision: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    getLoomWorkflowSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    getLoomPatternRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pattern_id: string;
                revision: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoomView"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    getLoomWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoomView"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    getNexusSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NexusSnapshot"];
                };
            };
        };
    };
    getNexusPlan: {
        parameters: {
            query: {
                target: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionPlan"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    createNexusSwap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwapIntent"];
            };
        };
        responses: {
            /** @description Request accepted, processing continues off-line */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapAccepted"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
            /** @description The durable request was already admitted but its process-local ticket is unavailable. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
            /** @description Process-local transition ticket capacity is temporarily exhausted. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    getNexusSwap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapAccepted"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    streamNexusSwapEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned semantic transition events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["TransitionEventEnvelope"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    getNexusTransition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionRecordView"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
    getOrbRun: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrbRunSnapshot"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
            /** @description Additional response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkError"];
                };
            };
        };
    };
}
