version = 1

[*]
c = 8192
n-gpu-layers = 99
cache-type-k = q8_0
cache-type-v = q8_0
flash-attn = true
jinja = true

[glm-4.5-air]
model = /models/glm_4.5_air/GLM-4.5-Air-Q4_K_M-00001-of-00002.gguf
load-on-startup = true
c = 90000
chat_template_kwargs = {"enable_thinking":false}

; Add more router targets as separate model sections.
; [qwen-local]
; model = /models/qwen/Qwen3-Next-Q4_K_M.gguf
; load-on-startup = false
